parameters:
    database_host: '%env(DB_HOST)%'
    database_name: '%env(DB_DATABASE)%'
    database_port: '%env(DB_PORT)%'
    database_user: '%env(DB_USERNAME)%'
    database_password: '%env(DB_PASSWORD)%'
    database_socket: '%env(DB_SOCKET)%'

    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    #env(DATABASE_URL): ''
    env(DB_HOST): ''
    env(DB_PORT): 3306
    env(DB_SOCKET): ''
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        unix_socket: '%database_socket%'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        types:
            localize_string: App\Type\LocalizeString


        #url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
