vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: /uploads/images/products
            upload_destination: '%env(UPLOAD_ROOT)%/products'

        article_images:
            uri_prefix: /uploads/images/articles
            upload_destination: '%env(UPLOAD_ROOT)%/articles'
